#!/usr/bin/env bash

if [ -f ./database.config ]; then
   docker build -t mpd-calldata .
else
   echo Please copy database.config_example with secrets to database.config , exiting build. Sad face.
fi
